In [39]:
import sklearn
import numpy as np
from sklearn import tree
from sklearn.datasets import load_iris
import pandas as pd
from numpy import ndarray
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import metrics
from sklearn.metrics import accuracy_score
from random import randint

In [2]:
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [3]:
print(iris.feature_names)
print(iris.target_names)
print(iris.data[0])
print(iris.target[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[5.1 3.5 1.4 0.2]
0


In [4]:
tests = [0, 50, 100]
training = np.delete(iris.target, tests)
traindata = np.delete(iris.data, tests, axis = 0)

testing = iris.target[tests]
testdata = iris.data[tests]

In [5]:
clf = tree.DecisionTreeClassifier()
clf.fit(traindata, training)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [6]:
print(testing)
print(clf.predict(testdata))

[0 1 2]
[0 1 2]


In [59]:
data = pd.read_csv("kickstarter data.csv", encoding="utf=8")
newdata = data[['launched_at', 'duration', 'goal_usd', 'start_month']]
# newdata = data[['launched_at', 'main_category', 'duration', 'goal_usd', 'start_month']]
results = data[['status']]
statuses = {"status":
                {"successful": 1, "failed": 0}}
results = results.replace(statuses)
# categories = {"main_category": {"dance": 0, "theater": 1, "design": 2, "publishing": 3, "comics": 4, "music": 5,
                              #"fashion": 6, "art": 7, "crafts": 8, "technology": 9, "film & video": 10, "games": 11,
                              #"food": 12, "photography": 13, "journalism": 14}}
# newdata = newdata.replace(categories)

newdata = newdata.to_numpy()
results = results.to_numpy()
results = np.ndarray.flatten(results)
newdata

array([[           nan,            nan,            nan,            nan],
       [4.19246000e+04, 3.00000000e+01, 5.00000000e+04, 1.00000000e+01],
       [           nan,            nan,            nan,            nan],
       ...,
       [4.19278000e+04, 3.00000000e+01, 9.06950304e+03, 1.00000000e+01],
       [           nan,            nan,            nan,            nan],
       [4.27544900e+04, 4.00000000e+01, 3.40106364e+03, 1.00000000e+00]])

In [ ]:
tests = [0, 30, 31, 32, 40, 50, 51, 55, 75, 90, 91, 92, 93, 94, 95, 100, 125, 150, 200, 300, 350, 500, 1000, 2500, 2600, 2700, 2750, 2800, 2850, 2851, 2852, 2900, 2950, 3000, 3100]
training = np.delete(results, tests)
traindata = np.delete(newdata, tests, axis = 0)

testing = results[tests]
testdata = newdata[tests]

In [58]:
clf = tree.DecisionTreeClassifier()
clf.fit(traindata, training)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [48]:
print(testing)
print(clf.predict(testdata))

[0 0 1 1 0 1 1 1 0 0 0 1 0 1 1 0 0 1 0 0 0 1 1 0 0 1 0 1 1 0 0 1 1 1 1]
[0 0 1 1 1 0 0 1 0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 0]


In [49]:
model = RandomForestClassifier(n_estimators=200, 
                               bootstrap = True,
                               max_features = 'sqrt')

model.fit(traindata, training)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='sqrt', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [52]:
print(testing)
print(model.predict(testdata))

[0 0 1 1 0 1 1 1 0 0 0 1 0 1 1 0 0 1 0 0 0 1 1 0 0 1 0 1 1 0 0 1 1 1 1]
[0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0]


In [53]:
kf = KFold(n_splits = 5)
kf.get_n_splits(newdata)

scores = cross_val_score(model, newdata, results, cv=3)
scores

array([0.64986601, 0.64194011, 0.64535228])

In [40]:
randoms = []
for i in range(3173):
    randoms.append(randint(0,1))
allsuccess = [1] * 3173

In [41]:
print("Random: " + str(accuracy_score(randoms, results)))
print("All Success: " + str(accuracy_score(allsuccess, results)))

Random: 0.4796722344784116
All Success: 0.7655215884021431


In [64]:
from scipy.stats import norm
norm.cdf(3, loc=0, scale=np.sqrt(2))

0.9830525732376554